services:
    bot:
        build:
            context: .
            dockerfile: ./Dockerfile.node
        restart: always
        depends_on:
            - redis

    redis:
        image: redis
        restart: always
