services:
    bot:
        build:
            context: .
            dockerfile: ./Dockerfile.node
        volumes:
            - type: bind
              source: .
              target: /usr/src/app
        restart: always
        depends_on:
            - redis

    redis:
        image: redis
        restart: always
