services:
    bot:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./config.prod.yml:/usr/src/app/config.yml
        restart: always
        depends_on:
            - mongo

    mongo:
        image: mongo
        restart: always
