on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    run_pull:
        name: run pull
        runs-on: ubuntu-latest
        steps:
            - name: deployment
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd ${{ secrets.WORK_DIR }}

                      ls -la

                      rm -rf ./*

                      #   cp ./config.example.yml ./config.prod.yml
                      #   sed -i -e 's/<mongo_connectionString>/mongodb:\/\/mongo:27017/g' ./config.prod.yml
                      #   sed -i -e 's/<mongo_databaseName>/subtle-team/g' ./config.prod.yml
                      #   sed -i -e 's/<telegram_botToken>/${{ secrets.BOT_TOKEN }}/g' ./config.prod.yml

                      #   cat config.prod.yml

                      #   docker compose up -d --build
